micronaut:
  application:
    name: micronaut-kafka-consumer-demo
  server:
    port: 9091
  h2:
    console.enabled: true

endpoints:
  health:
    sensitive: false

kafka:
  schema:
    registry:
      url: http://localhost:8081
  bootstrap:
    servers:
      - localhost:29092
  consumers:
    default:
      specific.avro.reader: true
      key.deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/herodb
    driverClassName: org.postgresql.Driver
    username: user
    password: pass
    schema-generate: CREATE_DROP
    dialect: POSTGRES