micronaut:
  application:
    name: micronaut-kafka-consumer-demo
  server:
    port: 9091

endpoints:
  health:
    sensitive: false

kafka:
  schema:
    registry:
      url: http://localhost:8081
  bootstrap:
    servers:
      - localhost:29092
  consumers:
    default:
      specific.avro.reader: true
      key.deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer